import { useWeb3React } from '@web3-react/core';
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import AvailableBonds from '../../lib/components/bond/AvailableBonds';
import KnowledgeBase from '../../lib/components/bond/KnowledgeBase';
import MyBonds from '../../lib/components/bond/MyBonds';
import PageTitle from '../../lib/components/common/PageTitle';
import { LoadErrorType } from '../../lib/types/common';

export default function Bond() {
  const router = useRouter();
  const query: any = router.query;
  const web3reactContext = useWeb3React();

  // loading state
  const [loading, setLoading] = useState<boolean>(true);

  // error state
  const [error, setError] = useState<null | LoadErrorType>(null);

  // initial product data
  const [bondData, setBondData] = useState<any>();

  useEffect(() => {
    setLoading(true);
    if (router.isReady) {
      axios
        .get(`/bond`)
        .then((res) => {
          setBondData(res.data[0]);
          setLoading(false);
        })
        .catch((err) => {
          setError({
            message: err.message,
            status: err.status,
            code: err.code,
          });
          setLoading(false);
        });
    }
  }, [router.isReady]);

  const InfoCard = ({ title, value }: { title: string; value: number }) => {
    return (
      <>
        <div className='info-card-wrapper'>
          <p>{title}</p>
          <h4>${value}</h4>
        </div>
        <style jsx>{`
          .info-card-wrapper {
            background-color: var(--cardBgPrimary);
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 20px;
            padding: 16px;
            border-radius: 10px;
            width: 354px;
          }
          p {
            color: var(--textLabel);
          }
        `}</style>
      </>
    );
  };

  return (
    <>
      <Head>
        {!loading && <title>{`Mozaic - Bond`}</title>}
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='bond-container'>
        <PageTitle
          title={'Bond'}
          rightElement={
            <div className='bond-info'>
              <InfoCard title='Treasury Balance' value={1234} />
              <InfoCard title='MOZ Price' value={1234} />
            </div>
          }
        />
        {web3reactContext.account && <MyBonds />}
        <AvailableBonds />
        <KnowledgeBase />
      </main>
      <style jsx>{`
        .bond-container {
          display: flex;
          flex-direction: column;
          align-items: center;
          height: 100%;
          width: 100%;
          gap: 32px;
          padding-bottom: 96px;
        }
        .bond-info {
          display: flex;
          gap: 10px;
        }
      `}</style>
    </>
  );
}
