import React from 'react';
import Head from 'next/head';
import PageTitle from '../../lib/components/common/PageTitle';
import { useRouter } from 'next/router';

export default function Product() {
  const router = useRouter();
  const query: any = router.query;

  return (
    <>
      <Head>
        <title>Mozaic - {query.name}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='product-container'>
        <PageTitle title={query.name} />
      </main>
      <style jsx>{``}</style>
    </>
  );
}
