import React from 'react';
import Head from 'next/head';
import PageTitle from '../../lib/components/common/PageTitle';
import { useRouter } from 'next/router';

export default function Product() {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>Mozaic - Products</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='product-container'>
        <PageTitle title='Our Products' />
      </main>
      <style jsx>{``}</style>
    </>
  );
}
