import Head from 'next/head';
import React, { useState } from 'react';
import PageTitle from '../../lib/components/common/PageTitle';
import DetailsSection from '../../lib/components/stake/DetailsSection';
import LockSection from '../../lib/components/stake/LockSection';
import OverviewSection from '../../lib/components/stake/OverviewSection';
import { TabItem } from '../../lib/types/common';

const title = { description: 'Automatic and intelligent multi-chain yield farming.', href: '#' };
const overviewData = [
  {
    id: 0,
    icon: '/assets/icons/assets/ico.moz.svg',
    duration: 1,
    name: 'veMOZ',
    amount: 0.33,
  },
  {
    id: 1,
    icon: '/assets/icons/assets/ico.moz.svg',
    duration: 2,
    name: 'veMOZ',
    amount: 0.66,
  },
  {
    id: 2,
    icon: '/assets/icons/assets/ico.moz.svg',
    duration: 3,
    name: 'veMOZ',
    amount: 0.99,
  },
];

const range: TabItem[] = [
  { id: 0, name: '1 week', shortName: '1W', value: 1 },
  { id: 1, name: '1 month', shortName: '1M', value: 4 },
  { id: 2, name: '3 Months', shortName: '3M', value: 13 },
  { id: 3, name: '6 Months', shortName: '6M', value: 26 },
  { id: 4, name: '1 Year', shortName: '1Y', value: 52 },
  { id: 5, name: '3 Years', shortName: '3Y', value: 156 },
];

const detailsData = {
  veMozBalance: 0,
  lockedMoz: 1521916216,
  totalVeMoz: 25351216551,
  averageLockTime: 3.64,
  tvl: 18156116136651,
};

const stakeAsset = {
  id: 3,
  name: 'AVAX',
  icon: '/assets/icons/assets/ico.avax.svg',
  address: '',
  decimals: 0,
  conversionRateUSD: 1,
  conversionRate: 3,
};

export default function Stake() {
  const [amount, setAmount] = useState(parseFloat(''));
  const [time, setTime] = useState();
  const [selectedRange, setSelectedRange] = useState<TabItem>(range[0]);
  const onLock = () => {};

  const setMaxBalance = (maxBalance: string) => {
    setAmount(parseFloat(maxBalance));
  };

  const onInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setAmount(parseFloat(e.target.value));
  };

  // Overview card section

  // Details card section

  // stake page layout

  return (
    <>
      <Head>
        <title>Mozaic - Stake</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='stake-container'>
        <PageTitle
          title='Stake'
          rightElement={
            <p className='description'>
              {title.description}
              <a className='learn-more' href={title.href}>
                Learn more <img src='/assets/icons/ico.next.svg' />
              </a>
            </p>
          }
        />
        <div className='stake-items-wrapper'>
          <section className='col left'>
            <OverviewSection data={overviewData} />
            <DetailsSection data={detailsData} />
          </section>
          <section className='col right'>
            <LockSection
              amount={amount}
              setMaxBalance={setMaxBalance}
              stakeAsset={stakeAsset}
              onInput={onInput}
              time={time}
              setTime={setTime}
              range={range}
              selectedRange={selectedRange}
              setSelectedRange={setSelectedRange}
              onLock={onLock}
            />
          </section>
        </div>
      </main>
      <style jsx>{`
        .stake-container {
          display: flex;
          flex-direction: column;
          align-items: center;
          height: 100%;
          width: 100%;
          gap: 32px;
          padding-bottom: 64px;
        }
        .description {
          display: flex;
          align-items: center;
          font-size: 0.875rem;
          gap: 10px;
          color: var(--textSecondary);
        }

        .learn-more {
          font-size: 0.875rem;
          color: var(--textPrimary);
          display: flex;
          gap: 4px;
          flex-direction: row;
          align-items: center;
          transition: all 0.2s ease;
        }

        .learn-more:hover {
          text-decoration: underline;
        }

        .stake-items-wrapper {
          display: flex;
          flex-direction: row;
          gap: 32px;
          width: 100%;
          flex-wrap: wrap;
        }

        .col {
          flex: 1;
          height: 100%;
          display: flex;
          flex-direction: column;
          gap: 32px;
        }
      `}</style>
    </>
  );
}
